// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    data_aggregator
    (
        init => init
        upgrade => upgrade
        addAdmin => add_admin_endpoint
        removeAdmin => remove_admin_endpoint
        getAdmins => admins
        registerApp => register_app_endpoint
        addDataCollection => add_data_collection_endpoint
        removeDataCollection => remove_data_collection_endpoint
        getAppInfo => get_app_info_view
        delegate => delegate_endpoint
        undelegate => undelegate_endpoint
        getDelegations => get_delegations_view
        getDelegationsByUser => get_delegations_by_user_view
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
